defmodule Gladius.ConformError do
  @moduledoc """
  Raised by the `!` variants generated by `defschema` when a value fails to
  conform to the schema.

  ## Fields

  - `:name`   — the schema name (atom) as passed to `defschema`
  - `:errors` — the full `[%Gladius.Error{}]` list from `Gladius.conform/2`
  """

  defexception [:name, :errors]

  @impl true
  def message(%{name: name, errors: errors}) do
    formatted =
      errors
      |> Enum.map(&to_string/1)
      |> Enum.join("\n  ")

    "#{inspect(name)} schema failed to conform:\n  #{formatted}"
  end
end
